spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_NAME}
    password: ${DB_PW}
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate:
      sql: debug
      type: trace

jwt:
  key: ${KEY}
  secret: ${SECRET}
  access: ${ACCESS_TIME}
  refresh: ${REFRESH_TIME}
  header: ${HEADER}

cloud.aws:
  region.static: ${REGION}
  credentials:
    secretKey: ${SECRETKEY}
    accessKey: ${ACCESSKEY}
  s3.bucket: ${BUCKET}
  stack.auto: false
  mail: ${EMAIL_SEND}
  template: ${TEMPLATE}

redis:
  port: ${REDIS_PORT}
  host: ${REDIS_HOST}
  password: ${REDIS_PW}